workflows:
  ios-workflow:
    name: iOS Release
    max_build_duration: 60
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: Quote English Daily
    
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        FCI_FLUTTER_SCHEME: manual
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.enjpbridge.app
    
    scripts:
      - name: Get Flutter packages
        script: |
          cd $CM_BUILD_DIR/app
          flutter pub get
      
      - name: Set up code signing
        script: |
          cd $CM_BUILD_DIR/app
          xcode-project use-profiles
      
      - name: Install CocoaPods
        script: |
          cd $CM_BUILD_DIR/app/ios
          pod install
      
      - name: Build iOS
        script: |
          cd $CM_BUILD_DIR/app
          flutter build ipa --release --export-options-plist=/Users/builder/export_options.plist
    
    artifacts:
      - app/build/ios/ipa/*.ipa
    
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false

  android-workflow:
    name: Android Release
    max_build_duration: 30
    instance_type: mac_mini_m2
    
    environment:
      flutter: stable
      java: 17
      vars:
        FCI_FLUTTER_SCHEME: manual
    
    scripts:
      - name: Get Flutter packages
        script: |
          cd $CM_BUILD_DIR/app
          flutter pub get
      
      - name: Build APK
        script: |
          cd $CM_BUILD_DIR/app
          flutter build apk --release
      
      - name: Build App Bundle
        script: |
          cd $CM_BUILD_DIR/app
          flutter build appbundle --release
    
    artifacts:
      - app/build/app/outputs/**/*.apk
      - app/build/app/outputs/**/*.aab
